Update ru_ru.json
LordDeatHunter/Alloy-Forgery pull request #104
Opened 2023-04-12 21:29 UTC by Heimdallr-1

2023-06-07 18:38 UTC, BasiqueEvangelist requested changes

2023-06-07 18:38 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.rei.fuel_per_tick": "Топливо в такт: %d",
Most russian-language resources use `тик` as a translation for tick.
Plus, honestly, the old translation is better here

2023-06-07 18:38 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.rei.button": "Переопределяет уровень цикла",
That's... not what it does? It cycles between the cycle overrides, it doesn't redefine anything.

2023-06-07 18:38 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.forge_controller": "Сплавная кузница",
Imo it would be still better to mention the fact that it's the controller of the forge, and not the entire forge.

2023-06-07 18:38 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "tooltip.alloy_forgery.fuel_capacity": "Объём топлива: %d",
"Вместимость" would probably be better here, as it's specifically how much there can be inside

2023-06-07 19:08 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.forge_controller": "Сплавная кузница",
Apparently I didn't look at the english translation, oops.

2023-06-07 19:08 UTC, Noaaan commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.forge_controller": "Сплавная кузница",
This context is inside the Alloy Forge, and in English intentionally does not reflect that it is inside the controller

2023-06-07 21:53 UTC, Heimdallr-1 commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.rei.fuel_per_tick": "Топливо в такт: %d",
Правильно будет написать слово **Такт**, поскольку в основном переводе майнкрафта написано именно **Такт**. Надо использовать правильное определение, а не полагаться на ошибочное.

2023-06-07 21:54 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.rei.fuel_per_tick": "Топливо в такт: %d",
Really? I thought that тик was the right word here, but sure. I'm just operating based on what feels right to me tbh.
~~also, can you link where specifically такт is used?~~

2023-06-07 21:59 UTC, BasiqueEvangelist commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.rei.fuel_per_tick": "Топливо в такт: %d",
Ah, I see, it's in the debug/perf commands and `argument.time.invalid_tick_count`. Still feels kinda wrong to me, but hey, it's Official™!

2023-06-08 18:05 UTC, Noaaan commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "tooltip.alloy_forgery.fuel_capacity": "Объём топлива: %d",
Would something like `Вместимость топлива: %d` be more appropiate then?

2023-06-08 18:46 UTC, Noaaan commented on src/main/resources/assets/alloy_forgery/lang/ru_ru.json
> +  "container.alloy_forgery.rei.button": "Переопределяет уровень цикла",
Any suggestions on something better for this?

2023-07-06 18:09 UTC, closed without merging