[i18n] Update zh_tw.json
LordDeatHunter/Alloy-Forgery pull request #74
Opened 2022-10-12 16:25 UTC by EvanHsieh0415

2022-10-13 10:58 UTC, StarskyXIII requested changes

2022-10-13 10:58 UTC, StarskyXIII commented on src/main/resources/assets/alloy_forgery/lang/zh_tw.json
> +  "block.alloy_forgery.prismarine_bricks_forge_controller": "海晶石磚冶煉控制器",
台灣譯作 `海磷石`，而非 `海晶石`

2022-10-13 10:58 UTC, StarskyXIII commented on src/main/resources/assets/alloy_forgery/lang/zh_tw.json
> +  "message.alloy_forgery.invalid_multiblock": "多方快結構無效",
選字錯誤，多方`塊`

2022-10-14 00:46 UTC, EvanHsieh0415 commented on src/main/resources/assets/alloy_forgery/lang/zh_tw.json
> +  "block.alloy_forgery.prismarine_bricks_forge_controller": "海晶石磚冶煉控制器",
已加到字典裡，感謝修正

2022-10-14 00:46 UTC, EvanHsieh0415 commented on src/main/resources/assets/alloy_forgery/lang/zh_tw.json
> +  "message.alloy_forgery.invalid_multiblock": "多方快結構無效",
感謝修正

2022-11-17 02:49 UTC, StarskyXIII approved these changes
All looks good now !

2022-12-03 10:53 UTC, SiongSng approved these changes

2023-02-20 00:13 UTC, Noaaan commented
Thank you for you contribution!

2023-02-20 00:13 UTC, merged